import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readdir,readFile} from 'node:fs/promises';
const root=new URL('../supabase/migrations/',import.meta.url);
test('migrações reais: retry atômico, estoque e isolamento por usuário',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
 create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
 for(const name of (await readdir(root)).filter(x=>x.endsWith('.sql')).sort()){
   // PGlite uses builtin gen_random_uuid; the production pgcrypto extension is unchanged.
   const sql=(await readFile(new URL(name,root),'utf8')).replace('create extension if not exists pgcrypto;','');
   await db.exec(sql);
 }
 await db.exec(await readFile(new URL('../seed.sql',root),'utf8'));
 assert.equal((await db.query('select count(distinct city)::int n from stores where active')).rows[0].n,9);
 assert.equal((await db.query('select count(*)::int n from products where active')).rows[0].n,153);
 const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
 await db.exec(`insert into auth.users(id,raw_user_meta_data) values ('${a}','{"legal_terms_version":"2026-09-28-v1","legal_privacy_version":"2026-09-28-v1"}'),('${b}','{"legal_terms_version":"2026-09-28-v1","legal_privacy_version":"2026-09-28-v1"}');
 insert into stores(public_id,name,city,service_areas,delivery_fee) values (9001,'Loja teste','Teste',array['Teste'],500);
 insert into products(public_id,store_id,name,price,stock) select 9001,id,'Produto teste',1200,10 from stores where public_id=9001;`);
 await db.exec(`update stores set delivery_fee=500,delivery_fee_per_km=0,delivery_minimum_fee=0 where public_id=9001;`);
 await db.exec(`insert into store_members(store_id,user_id,role) select id,'${b}','owner' from stores where public_id=9001;`);
 const request='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
 const call=(qty=2)=>db.query(`select * from public.create_order_once($1,9001,'Teste','delivery','Cliente Teste','88999999999','Rua Teste 100','Centro','','pix',$2::jsonb)`,[request,JSON.stringify([{productId:9001,quantity:qty}])]);
 const asUser=async id=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);`);
 await asUser(a);const first=(await call()).rows[0],again=(await call()).rows[0];assert.deepEqual(first,again);assert.equal(first.total,2900);
 await assert.rejects(call(3),/order_request_conflict/);
 await assert.rejects(db.query(`select * from public.create_order_once('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',9001,'Teste','delivery','Cliente Teste','88999999999','Rua Teste 100','Centro','','pix','[{"productId":9001,"quantity":99}]')`),/insufficient_stock/);
 await db.exec('reset role');assert.equal((await db.query('select stock from products where public_id=9001')).rows[0].stock,8);
 assert.equal((await db.query('select count(*)::int n from orders')).rows[0].n,1);
 await asUser(a);assert.equal((await db.query("update orders set status='preparing' where id=$1 returning id",[first.order_id])).rows.length,0);
 await db.exec('reset role;delete from store_members');
 await asUser(b);assert.equal((await db.query('select count(*)::int n from orders')).rows[0].n,0);
 const second=(await call()).rows[0];assert.notEqual(second.order_id,first.order_id);
 assert.equal((await db.query('select count(*)::int n from orders')).rows[0].n,1);
 await db.exec('reset role');
 await db.exec(`insert into store_members(store_id,user_id,role) select id,'${b}','owner' from stores where public_id=9001;`);
 await asUser(b);await assert.rejects(db.query('update stores set delivery_fee=9999 where public_id=9001'),/permission denied/);
 assert.equal((await db.query("update orders set status='preparing' where id=$1 returning id",[first.order_id])).rows.length,1);
 await assert.rejects(db.query("update orders set status='pending' where id=$1",[first.order_id]),/invalid_order_status_transition/);
 await assert.rejects(db.query('select * from private.checkout_requests'),/permission denied/);
 await db.exec("reset role;set role anon;select set_config('request.jwt.claim.sub','',false)");await assert.rejects(call(),/permission denied/);
 await db.exec('reset role');assert.equal((await db.query('select stock from products where public_id=9001')).rows[0].stock,6);
 await db.exec(`insert into products(public_id,store_id,name,price,old_price,last_batch,stock,offer_starts_at,offer_ends_at)
 select 9002,id,'Oferta teste',1500,2000,true,10,now()-interval '1 hour',now()+interval '1 hour' from stores where public_id=9001;`);
 const offerOrder=expected=>db.query(`select * from public.create_order_once($1,9001,'Teste','pickup','Cliente Teste','88999999999','','','','pix',$2::jsonb)`,[crypto.randomUUID(),JSON.stringify([{productId:9002,quantity:1,expectedPrice:expected}])]);
 await asUser(a);assert.equal((await offerOrder(1500)).rows[0].total,1500);
 await db.exec(`reset role;alter table products disable trigger products_validate_offer_dates;
 update products set offer_starts_at=now()-interval '2 hours',offer_ends_at=now()-interval '1 hour' where public_id=9002;
 alter table products enable trigger products_validate_offer_dates;`);
 await asUser(a);await assert.rejects(offerOrder(1500),/price_changed/);
 await db.exec('reset role');assert.equal((await db.query('select stock from products where public_id=9002')).rows[0].stock,9);
 await asUser(a);assert.equal((await offerOrder(2000)).rows[0].total,2000);
 await db.exec(`reset role;update products set offer_starts_at=now()+interval '1 hour',offer_ends_at=now()+interval '2 hours' where public_id=9002;`);
 await asUser(a);assert.equal((await offerOrder(2000)).rows[0].total,2000);
 await db.exec('reset role');
 await assert.rejects(db.exec('update products set offer_starts_at=null,offer_ends_at=null where public_id=9002'),/invalid_offer_window/);
 await assert.rejects(db.exec("update products set offer_starts_at=now(),offer_ends_at=now()-interval '1 hour' where public_id=9002"),/invalid_offer_window/);
 await db.exec(`reset role;update stores set delivery_fee=0,delivery_fee_per_km=150,delivery_minimum_fee=300 where public_id=9001;`);
 assert.equal((await db.query('select private.delivery_fee_for(200,100,500,3) fee')).rows[0].fee,500);
 assert.equal((await db.query('select private.delivery_fee_for(200,100,500,10) fee')).rows[0].fee,1200);
 assert.equal((await db.query('select private.delivery_fee_for(0,150,300,2) fee')).rows[0].fee,300);
 assert.equal((await db.query('select private.delivery_fee_for(500,150,0,3) fee')).rows[0].fee,950);
 await asUser(a);
 const distanceRequest='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
 const distanceOrder=(km=4,expected=600)=>db.query(`select * from public.create_order_distance_once($1,9001,'Teste','delivery','Cliente Teste','88999999999','Rua Teste 100','Centro','','pix','[{"productId":9001,"quantity":1}]',$2,$3)`,[distanceRequest,km,expected]);
 await assert.rejects(distanceOrder(4,1),/delivery_price_changed/);
 await assert.rejects(distanceOrder(-1,600),/invalid_delivery_distance/);
 await assert.rejects(distanceOrder(null,600),/distance_required/);
 const distanceCreated=(await distanceOrder()).rows[0];
 assert.equal(distanceCreated.delivery_fee,600);assert.equal(distanceCreated.total,1800);
 assert.deepEqual((await distanceOrder()).rows[0],distanceCreated);
 await assert.rejects(distanceOrder(5,750),/order_request_conflict/);
 const snapshot=(await db.query('select delivery_distance_km,delivery_rate_per_km,delivery_base_fee,delivery_minimum_fee from orders where id=$1',[distanceCreated.order_id])).rows[0];
 assert.equal(Number(snapshot.delivery_distance_km),4);assert.equal(snapshot.delivery_rate_per_km,150);assert.equal(snapshot.delivery_base_fee,0);assert.equal(snapshot.delivery_minimum_fee,300);
 await assert.rejects(db.query(`select * from public.create_order_once('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',9001,'Teste','delivery','Cliente Teste','88999999999','Rua Teste 100','Centro','','pix','[{"productId":9001,"quantity":1}]')`),/distance_required/);
 await db.exec('reset role;set role anon');
 await assert.rejects(distanceOrder(),/permission denied/);
 }finally{await db.close();}
});
