-- APETÊ backend v1
-- Auth + catálogo + pedidos + comerciante + entregas.
create extension if not exists pgcrypto;

create type public.apete_profile_role as enum ('customer','merchant','courier','admin');
create type public.apete_store_member_role as enum ('owner','manager','staff');
create type public.apete_order_status as enum ('pending','accepted','preparing','ready','out_for_delivery','delivered','cancelled');
create type public.apete_delivery_status as enum ('assigned','picked_up','delivered','cancelled');
create type public.apete_merchant_application_status as enum ('pending','approved','rejected');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.apete_profile_role not null default 'customer',
  full_name text not null default '',
  phone text not null default '',
  address text not null default '',
  neighborhood text not null default '',
  city text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.stores (
  id uuid primary key default gen_random_uuid(),
  public_id bigint generated by default as identity unique not null,
  name text not null check (char_length(name) between 2 and 100),
  category text not null default '',
  city text not null,
  description text not null default '',
  hero text not null default '',
  delivery_fee integer not null default 0 check (delivery_fee >= 0),
  producer boolean not null default false,
  delivery boolean not null default true,
  pickup boolean not null default true,
  service_areas text[] not null default '{}',
  cover text not null default '',
  verified boolean not null default false,
  active boolean not null default true,
  demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.store_members (
  store_id uuid not null references public.stores(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.apete_store_member_role not null default 'staff',
  created_at timestamptz not null default now(),
  primary key (store_id,user_id)
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  public_id bigint generated by default as identity unique not null,
  store_id uuid not null references public.stores(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 120),
  description text not null default '',
  category text not null default '',
  price integer not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  image text not null default '',
  old_price integer not null default 0 check (old_price >= 0),
  last_batch boolean not null default false,
  preferences text[] not null default '{}',
  serves integer check (serves is null or serves > 0),
  active boolean not null default true,
  demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  public_number bigint generated always as identity unique not null,
  customer_id uuid not null references public.profiles(id) on delete restrict,
  store_id uuid not null references public.stores(id) on delete restrict,
  status public.apete_order_status not null default 'pending',
  mode text not null check (mode in ('delivery','pickup')),
  city text not null,
  customer_name text not null,
  customer_phone text not null,
  address text not null default '',
  neighborhood text not null default '',
  note text not null default '',
  payment_method text not null check (payment_method in ('pix','card','card_on_delivery')),
  subtotal integer not null check (subtotal >= 0),
  delivery_fee integer not null check (delivery_fee >= 0),
  total integer not null check (total >= 0 and total = subtotal + delivery_fee),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 99),
  line_subtotal integer not null check (line_subtotal >= 0 and line_subtotal = unit_price * quantity),
  created_at timestamptz not null default now()
);

create table public.delivery_assignments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  courier_id uuid not null references public.profiles(id) on delete restrict,
  status public.apete_delivery_status not null default 'assigned',
  assigned_at timestamptz not null default now(),
  picked_up_at timestamptz,
  delivered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.merchant_applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  store_name text not null,
  phone text not null,
  city text not null,
  document text not null,
  instagram text not null,
  status public.apete_merchant_application_status not null default 'pending',
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index orders_customer_idx on public.orders(customer_id,created_at desc);
create index orders_store_idx on public.orders(store_id,created_at desc);
create index orders_status_idx on public.orders(status,created_at desc);
create index products_store_idx on public.products(store_id,active);
create index store_members_user_idx on public.store_members(user_id);
create index delivery_courier_idx on public.delivery_assignments(courier_id,status);
create index merchant_applications_user_idx on public.merchant_applications(user_id,created_at desc);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at=now();
  return new;
end $$;

create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
create trigger stores_touch before update on public.stores for each row execute function public.touch_updated_at();
create trigger products_touch before update on public.products for each row execute function public.touch_updated_at();
create trigger orders_touch before update on public.orders for each row execute function public.touch_updated_at();
create trigger delivery_touch before update on public.delivery_assignments for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.profiles(id,full_name,phone)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'phone',''))
  on conflict(id) do nothing;
  return new;
end $$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles p where p.id=uid and p.role='admin') $$;

create or replace function public.is_store_member(target_store uuid, uid uuid default auth.uid())
returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.store_members sm where sm.store_id=target_store and sm.user_id=uid) $$;

create or replace function public.can_access_order(target_order uuid, uid uuid default auth.uid())
returns boolean
language sql stable security definer set search_path=public
as $$
select exists(
  select 1
  from public.orders o
  where o.id=target_order
    and (
      o.customer_id=uid
      or public.is_store_member(o.store_id,uid)
      or public.is_admin(uid)
      or exists(select 1 from public.delivery_assignments d where d.order_id=o.id and d.courier_id=uid)
    )
) $$;

grant execute on function public.is_admin(uuid) to authenticated;
grant execute on function public.is_store_member(uuid,uuid) to authenticated;
grant execute on function public.can_access_order(uuid,uuid) to authenticated;

create or replace function public.valid_order_transition(old_status public.apete_order_status,new_status public.apete_order_status)
returns boolean language sql immutable as $$
select case old_status
 when 'pending' then new_status in ('accepted','cancelled')
 when 'accepted' then new_status in ('preparing','cancelled')
 when 'preparing' then new_status in ('ready','cancelled')
 when 'ready' then new_status in ('out_for_delivery','delivered','cancelled')
 when 'out_for_delivery' then new_status in ('delivered','cancelled')
 else false end
$$;

create or replace function public.enforce_order_status_transition()
returns trigger language plpgsql as $$
begin
  if new.status is distinct from old.status and not public.valid_order_transition(old.status,new.status) then
    raise exception 'invalid_order_status_transition' using errcode='22023';
  end if;
  return new;
end $$;

create trigger orders_status_transition
before update of status on public.orders
for each row execute function public.enforce_order_status_transition();

alter table public.profiles enable row level security;
alter table public.stores enable row level security;
alter table public.store_members enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.delivery_assignments enable row level security;
alter table public.merchant_applications enable row level security;

create policy profiles_self_select on public.profiles for select to authenticated
using (id=auth.uid() or public.is_admin());
create policy profiles_self_update on public.profiles for update to authenticated
using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());

create policy stores_public_read on public.stores for select to anon,authenticated using (active);
create policy stores_member_update on public.stores for update to authenticated
using (public.is_store_member(id) or public.is_admin())
with check (public.is_store_member(id) or public.is_admin());

create policy members_self_read on public.store_members for select to authenticated
using (user_id=auth.uid() or public.is_admin());
create policy members_admin_write on public.store_members for all to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy products_public_read on public.products for select to anon,authenticated
using (active and exists(select 1 from public.stores s where s.id=store_id and s.active));
create policy products_member_insert on public.products for insert to authenticated
with check (public.is_store_member(store_id) or public.is_admin());
create policy products_member_update on public.products for update to authenticated
using (public.is_store_member(store_id) or public.is_admin())
with check (public.is_store_member(store_id) or public.is_admin());
create policy products_member_delete on public.products for delete to authenticated
using (public.is_store_member(store_id) or public.is_admin());

create policy orders_read on public.orders for select to authenticated
using (
 customer_id=auth.uid()
 or public.is_store_member(store_id)
 or public.is_admin()
 or exists(select 1 from public.delivery_assignments d where d.order_id=id and d.courier_id=auth.uid())
);
create policy orders_staff_status_update on public.orders for update to authenticated
using (
 public.is_store_member(store_id)
 or public.is_admin()
 or exists(select 1 from public.delivery_assignments d where d.order_id=id and d.courier_id=auth.uid())
)
with check (
 public.is_store_member(store_id)
 or public.is_admin()
 or exists(select 1 from public.delivery_assignments d where d.order_id=id and d.courier_id=auth.uid())
);

create policy order_items_read on public.order_items for select to authenticated
using (public.can_access_order(order_id));

create policy deliveries_read on public.delivery_assignments for select to authenticated
using (
 courier_id=auth.uid()
 or public.is_admin()
 or exists(select 1 from public.orders o where o.id=order_id and public.is_store_member(o.store_id))
);
create policy deliveries_admin_write on public.delivery_assignments for insert to authenticated
with check (public.is_admin());
create policy deliveries_update on public.delivery_assignments for update to authenticated
using (courier_id=auth.uid() or public.is_admin())
with check (courier_id=auth.uid() or public.is_admin());

create policy applications_own_read on public.merchant_applications for select to authenticated
using (user_id=auth.uid() or public.is_admin());
create policy applications_own_insert on public.merchant_applications for insert to authenticated
with check (user_id=auth.uid() and status='pending');
create policy applications_admin_update on public.merchant_applications for update to authenticated
using (public.is_admin()) with check (public.is_admin());

revoke all on public.profiles,public.stores,public.store_members,public.products,public.orders,public.order_items,public.delivery_assignments,public.merchant_applications from anon,authenticated;
grant select on public.stores,public.products to anon,authenticated;
grant select on public.profiles,public.store_members,public.orders,public.order_items,public.delivery_assignments,public.merchant_applications to authenticated;
grant update(full_name,phone,address,neighborhood,city,updated_at) on public.profiles to authenticated;
grant update(name,category,city,description,hero,delivery_fee,producer,delivery,pickup,service_areas,cover,updated_at) on public.stores to authenticated;
grant insert,update,delete on public.products to authenticated;
grant update(status,updated_at) on public.orders to authenticated;
grant insert,update on public.delivery_assignments to authenticated;
grant insert(user_id,store_name,phone,city,document,instagram,status) on public.merchant_applications to authenticated;
grant update(status,reviewed_by,reviewed_at) on public.merchant_applications to authenticated;
grant insert,update,delete on public.store_members to authenticated;

create or replace function public.create_order(
  p_store_public_id bigint,
  p_city text,
  p_mode text,
  p_customer_name text,
  p_customer_phone text,
  p_address text,
  p_neighborhood text,
  p_note text,
  p_payment_method text,
  p_items jsonb
)
returns table(order_id uuid,public_number bigint,subtotal integer,delivery_fee integer,total integer)
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid:=auth.uid();
  target_store public.stores%rowtype;
  entry jsonb;
  prod public.products%rowtype;
  qty integer;
  sub integer:=0;
  fee integer:=0;
  created_order public.orders%rowtype;
begin
  if uid is null then raise exception 'authentication_required' using errcode='28000'; end if;
  if p_mode not in ('delivery','pickup') then raise exception 'invalid_mode' using errcode='22023'; end if;
  if p_payment_method not in ('pix','card','card_on_delivery') then raise exception 'invalid_payment_method' using errcode='22023'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 or jsonb_array_length(p_items)>30 then
    raise exception 'invalid_items' using errcode='22023';
  end if;

  select * into target_store from public.stores where public_id=p_store_public_id and active for update;
  if not found then raise exception 'store_unavailable' using errcode='P0002'; end if;
  if p_mode='delivery' and not target_store.delivery then raise exception 'delivery_unavailable' using errcode='22023'; end if;
  if p_mode='pickup' and not target_store.pickup then raise exception 'pickup_unavailable' using errcode='22023'; end if;
  if target_store.city<>p_city and not (p_city=any(target_store.service_areas)) then raise exception 'city_unavailable' using errcode='22023'; end if;

  create temporary table if not exists pg_temp.apete_order_lines(
    product_id uuid,product_name text,unit_price integer,quantity integer,line_subtotal integer
  ) on commit drop;
  truncate pg_temp.apete_order_lines;

  for entry in select value from jsonb_array_elements(p_items)
  loop
    qty:=coalesce((entry->>'quantity')::integer,0);
    if qty<1 or qty>99 then raise exception 'invalid_quantity' using errcode='22023'; end if;
    select * into prod
      from public.products
      where public_id=(entry->>'productId')::bigint and active
      for update;
    if not found then raise exception 'product_unavailable' using errcode='P0002'; end if;
    if prod.store_id<>target_store.id then raise exception 'mixed_store_order' using errcode='22023'; end if;
    if prod.stock<qty then raise exception 'insufficient_stock' using errcode='22023'; end if;
    insert into pg_temp.apete_order_lines values(prod.id,prod.name,prod.price,qty,prod.price*qty);
    sub:=sub+(prod.price*qty);
  end loop;

  fee:=case when p_mode='delivery' then target_store.delivery_fee else 0 end;

  insert into public.orders(
    customer_id,store_id,status,mode,city,customer_name,customer_phone,address,neighborhood,note,payment_method,subtotal,delivery_fee,total
  ) values(
    uid,target_store.id,'pending',p_mode,p_city,trim(p_customer_name),trim(p_customer_phone),
    case when p_mode='delivery' then trim(p_address) else '' end,trim(p_neighborhood),coalesce(trim(p_note),''),
    p_payment_method,sub,fee,sub+fee
  ) returning * into created_order;

  insert into public.order_items(order_id,product_id,product_name,unit_price,quantity,line_subtotal)
  select created_order.id,product_id,product_name,unit_price,quantity,line_subtotal from pg_temp.apete_order_lines;

  update public.products p
     set stock=p.stock-l.quantity
    from pg_temp.apete_order_lines l
   where p.id=l.product_id;

  return query select created_order.id,created_order.public_number,sub,fee,sub+fee;
end $$;

revoke all on function public.create_order(bigint,text,text,text,text,text,text,text,text,jsonb) from public;
grant execute on function public.create_order(bigint,text,text,text,text,text,text,text,text,jsonb) to authenticated;

