-- Descrições de exemplos e imagens ilustrativas; sem fotos de carne em pratos vegetarianos.
update public.products set image='assets/images/prod-galinha.webp',description='Arroz com frango desfiado e legumes. Porção individual demonstrativa.' where demo and public_id=1001;
update public.products set image='',description='Carne de panela com arroz, feijão e legumes. Porção individual demonstrativa.' where demo and public_id=1002;
update public.products set image='assets/images/prod-almoco-veg.webp',description='Porção individual de arroz, feijão, legumes e salada, sem carne. Receita demonstrativa.' where demo and public_id=1003;
update public.products set image='',description='Filé de peixe com purê de macaxeira e salada. Porção individual demonstrativa.' where demo and public_id=1004;
update public.products set image='assets/images/prod-caja.webp',description='Suco de cajá em copo de 400 ml. Produto demonstrativo.' where demo and public_id=1005;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1006;
update public.products set image='assets/images/prod-tapioca.webp',description='Tapioca com queijo coalho, unidade individual. Produto demonstrativo.' where demo and public_id=1007;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1008;
update public.products set image='assets/images/prod-bolo-milho.webp',description='Fatia individual de bolo de milho. Produto demonstrativo.' where demo and public_id=1009;
update public.products set image='assets/images/prod-cafe-coado.webp',description='Café coado sem leite, copo de 200 ml. Produto demonstrativo.' where demo and public_id=1010;
update public.products set image='assets/images/prod-cesta-hortalicas.webp',description='Cesta demonstrativa com alface, tomate, cenoura e cheiro-verde.' where demo and public_id=1011;
update public.products set image='assets/images/prod-banana.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1012;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1013;
update public.products set image='assets/images/prod-geleia-goiaba.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1014;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1015;
update public.products set image='assets/images/prod-almoco-veg.webp',description='Porção individual de arroz, feijão, legumes e salada, sem carne. Receita demonstrativa.' where demo and public_id=1016;
update public.products set image='',description='Carne de panela com arroz, feijão e legumes. Porção individual demonstrativa.' where demo and public_id=1017;
update public.products set image='assets/images/prod-almoco-veg.webp',description='Porção individual de arroz, feijão, legumes e salada, sem carne. Receita demonstrativa.' where demo and public_id=1018;
update public.products set image='',description='Filé de peixe com purê de macaxeira e salada. Porção individual demonstrativa.' where demo and public_id=1019;
update public.products set image='assets/images/prod-caja.webp',description='Suco de cajá em copo de 400 ml. Produto demonstrativo.' where demo and public_id=1020;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1021;
update public.products set image='assets/images/prod-tapioca.webp',description='Tapioca com queijo coalho, unidade individual. Produto demonstrativo.' where demo and public_id=1022;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1023;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1024;
update public.products set image='assets/images/prod-cafe-coado.webp',description='Café coado sem leite, copo de 200 ml. Produto demonstrativo.' where demo and public_id=1025;
update public.products set image='assets/images/prod-cesta-hortalicas.webp',description='Cesta demonstrativa com alface, tomate, cenoura e cheiro-verde.' where demo and public_id=1026;
update public.products set image='assets/images/prod-banana.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1027;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1028;
update public.products set image='assets/images/prod-geleia-goiaba.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1029;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1030;
update public.products set image='',description='Porção individual de purê de macaxeira com legumes, preparada sem carne, leite ou queijo. Receita demonstrativa.' where demo and public_id=1031;
update public.products set image='',description='Carne de panela com arroz, feijão e legumes. Porção individual demonstrativa.' where demo and public_id=1032;
update public.products set image='assets/images/prod-almoco-veg.webp',description='Porção individual de arroz, feijão, legumes e salada, sem carne. Receita demonstrativa.' where demo and public_id=1033;
update public.products set image='',description='Filé de peixe com purê de macaxeira e salada. Porção individual demonstrativa.' where demo and public_id=1034;
update public.products set image='assets/images/prod-caja.webp',description='Suco de cajá em copo de 400 ml. Produto demonstrativo.' where demo and public_id=1035;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1036;
update public.products set image='assets/images/prod-tapioca.webp',description='Tapioca com queijo coalho, unidade individual. Produto demonstrativo.' where demo and public_id=1037;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1038;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1039;
update public.products set image='assets/images/prod-cafe-coado.webp',description='Café coado sem leite, copo de 200 ml. Produto demonstrativo.' where demo and public_id=1040;
update public.products set image='assets/images/prod-cesta-hortalicas.webp',description='Cesta demonstrativa com alface, tomate, cenoura e cheiro-verde.' where demo and public_id=1041;
update public.products set image='assets/images/prod-banana.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1042;
update public.products set image='assets/images/prod-tomate.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1043;
update public.products set image='assets/images/prod-geleia-goiaba.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1044;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1045;
update public.products set image='assets/images/prod-galinha.webp',description='Frango acompanhado de cuscuz de milho e salada. Porção individual demonstrativa.' where demo and public_id=1046;
update public.products set image='',description='Carne de panela com arroz, feijão e legumes. Porção individual demonstrativa.' where demo and public_id=1047;
update public.products set image='assets/images/prod-almoco-veg.webp',description='Porção individual de arroz, feijão, legumes e salada, sem carne. Receita demonstrativa.' where demo and public_id=1048;
update public.products set image='',description='Filé de peixe com purê de macaxeira e salada. Porção individual demonstrativa.' where demo and public_id=1049;
update public.products set image='assets/images/prod-caja.webp',description='Suco de cajá em copo de 400 ml. Produto demonstrativo.' where demo and public_id=1050;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1051;
update public.products set image='assets/images/prod-tapioca.webp',description='Tapioca com queijo coalho, unidade individual. Produto demonstrativo.' where demo and public_id=1052;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1053;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1054;
update public.products set image='assets/images/prod-cafe-coado.webp',description='Café coado sem leite, copo de 200 ml. Produto demonstrativo.' where demo and public_id=1055;
update public.products set image='assets/images/prod-cesta-hortalicas.webp',description='Cesta demonstrativa com alface, tomate, cenoura e cheiro-verde.' where demo and public_id=1056;
update public.products set image='assets/images/prod-banana.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1057;
update public.products set image='assets/images/prod-cenoura.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1058;
update public.products set image='assets/images/prod-geleia-goiaba.webp',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1059;
update public.products set image='',description='Produto de exemplo. O tamanho ou a quantidade estão indicados no nome.' where demo and public_id=1060;
update public.products set image='assets/images/prod-almoco-veg.webp',description='Porção individual de arroz, feijão, legumes e salada, sem carne. Receita demonstrativa.' where demo and public_id=1061;
update public.products set image='assets/images/prod-almoco-veg.webp',description='Porção individual de arroz, feijão, legumes e salada, sem carne. Receita demonstrativa.' where demo and public_id=1062;
update public.products set image='',description='Porção individual de purê de macaxeira com legumes, preparada sem carne, leite ou queijo. Receita demonstrativa.' where demo and public_id=1063;
