-- Product-specific and establishment-specific illustrative photos.
-- Guard existing names and old assets to preserve intervening merchant uploads.
update public.products set image = 'assets/images/photo-product-1-v2.webp' where demo = true and public_id = 1 and name = 'Baião da casa para dois' and image = 'assets/images/prod-baiao.webp';
update public.products set image = 'assets/images/photo-product-7-v2.webp' where demo = true and public_id = 7 and name = 'Bolo de milho caseiro' and image = 'assets/images/prod-bolo-milho.webp';
update public.products set image = 'assets/images/photo-product-9-v2.webp' where demo = true and public_id = 9 and name = 'Café coado' and image = 'assets/images/prod-cafe-coado.webp';
update public.products set image = 'assets/images/photo-product-13-v2.webp' where demo = true and public_id = 13 and name = 'Almoço vegetariano' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-25-v2.webp' where demo = true and public_id = 25 and name = 'Queijo coalho artesanal' and image = 'assets/images/prod-queijo-coalho.webp';
update public.products set image = 'assets/images/photo-product-26-v2.webp' where demo = true and public_id = 26 and name = 'Pão francês da fornada' and image = 'assets/images/product-bakery.webp';
update public.products set image = 'assets/images/photo-product-27-v2.webp' where demo = true and public_id = 27 and name = 'Sonho de creme' and image = 'assets/images/product-bakery.webp';
update public.products set image = 'assets/images/photo-product-28-v2.webp' where demo = true and public_id = 28 and name = 'Bolo fofo de laranja' and image = 'assets/images/prod-bolo-milho.webp';
update public.products set image = 'assets/images/photo-product-29-v2.webp' where demo = true and public_id = 29 and name = 'Cuscuz com queijo coalho' and image = 'assets/images/prod-tapioca.webp';
update public.products set image = 'assets/images/photo-product-30-v2.webp' where demo = true and public_id = 30 and name = 'Kit fim de fornada' and image = 'assets/images/product-bakery.webp';
update public.products set image = 'assets/images/photo-product-31-v2.webp' where demo = true and public_id = 31 and name = 'Pão de coco' and image = 'assets/images/product-bakery.webp';
update public.products set image = 'assets/images/photo-product-32-v2.webp' where demo = true and public_id = 32 and name = 'Croissant de queijo' and image = 'assets/images/product-bakery.webp';
update public.products set image = 'assets/images/photo-product-33-v2.webp' where demo = true and public_id = 33 and name = 'Pão de queijo' and image = 'assets/images/prod-queijo-coalho.webp';
update public.products set image = 'assets/images/photo-product-34-v2.webp' where demo = true and public_id = 34 and name = 'Bolo de macaxeira' and image = 'assets/images/product-bakery.webp';
update public.products set image = 'assets/images/photo-product-35-v2.webp' where demo = true and public_id = 35 and name = 'Cesta da fornada do dia' and image = 'assets/images/product-bakery.webp';
update public.products set image = 'assets/images/photo-product-36-v2.webp' where demo = true and public_id = 36 and name = 'Brownie de chocolate' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-37-v2.webp' where demo = true and public_id = 37 and name = 'Brigadeiro artesanal' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-38-v2.webp' where demo = true and public_id = 38 and name = 'Bolo no pote de ninho' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-39-v2.webp' where demo = true and public_id = 39 and name = 'Pudim caseiro' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-40-v2.webp' where demo = true and public_id = 40 and name = 'Caixa mini doces' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-41-v2.webp' where demo = true and public_id = 41 and name = 'Fatia red velvet' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-42-v2.webp' where demo = true and public_id = 42 and name = 'Churros com doce de leite' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-43-v2.webp' where demo = true and public_id = 43 and name = 'Palha italiana' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-44-v2.webp' where demo = true and public_id = 44 and name = 'Copo da felicidade' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-45-v2.webp' where demo = true and public_id = 45 and name = 'Bolo de cenoura com chocolate' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-46-v2.webp' where demo = true and public_id = 46 and name = 'Torta de chocolate' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-47-v2.webp' where demo = true and public_id = 47 and name = 'Cheesecake de frutas vermelhas' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-48-v2.webp' where demo = true and public_id = 48 and name = 'Cappuccino da casa' and image = 'assets/images/prod-cafe-serra.webp';
update public.products set image = 'assets/images/photo-product-49-v2.webp' where demo = true and public_id = 49 and name = 'Brownie com sorvete' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-50-v2.webp' where demo = true and public_id = 50 and name = 'Caixa de trufas' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-51-v2.webp' where demo = true and public_id = 51 and name = 'X-burger da casa' and image = 'assets/images/product-regional.webp';
update public.products set image = 'assets/images/photo-product-52-v2.webp' where demo = true and public_id = 52 and name = 'Sanduíche de frango' and image = 'assets/images/product-regional.webp';
update public.products set image = 'assets/images/photo-product-53-v2.webp' where demo = true and public_id = 53 and name = 'Batata frita crocante' and image = 'assets/images/product-regional.webp';
update public.products set image = 'assets/images/photo-product-54-v2.webp' where demo = true and public_id = 54 and name = 'Cachorro-quente completo' and image = 'assets/images/product-regional.webp';
update public.products set image = 'assets/images/photo-product-55-v2.webp' where demo = true and public_id = 55 and name = 'Suco de cajá 400 ml' and image = 'assets/images/prod-caja.webp';
update public.products set image = 'assets/images/photo-product-56-v2.webp' where demo = true and public_id = 56 and name = 'Cuscuz com carne de sol' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-57-v2.webp' where demo = true and public_id = 57 and name = 'Cuscuz com ovo e queijo' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-58-v2.webp' where demo = true and public_id = 58 and name = 'Tapioca de frango' and image = 'assets/images/prod-tapioca.webp';
update public.products set image = 'assets/images/photo-product-59-v2.webp' where demo = true and public_id = 59 and name = 'Café com leite' and image = 'assets/images/prod-cafe-coado.webp';
update public.products set image = 'assets/images/photo-product-60-v2.webp' where demo = true and public_id = 60 and name = 'Bolo pé de moleque' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-61-v2.webp' where demo = true and public_id = 61 and name = 'Pizza muçarela média' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-62-v2.webp' where demo = true and public_id = 62 and name = 'Pizza calabresa média' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-63-v2.webp' where demo = true and public_id = 63 and name = 'Pizza frango cremosa média' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-64-v2.webp' where demo = true and public_id = 64 and name = 'Pizza marguerita média' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-65-v2.webp' where demo = true and public_id = 65 and name = 'Combo pizza e refrigerante' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-66-v2.webp' where demo = true and public_id = 66 and name = 'Marmita de frango grelhado' and image = 'assets/images/prod-prato-serra.webp';
update public.products set image = 'assets/images/photo-product-67-v2.webp' where demo = true and public_id = 67 and name = 'Carne de panela completa' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-68-v2.webp' where demo = true and public_id = 68 and name = 'Peixe grelhado com legumes' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-69-v2.webp' where demo = true and public_id = 69 and name = 'Marmita vegetariana' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-70-v2.webp' where demo = true and public_id = 70 and name = 'Feijoada individual' and image = 'assets/images/product-caseiro.webp';
update public.products set image = 'assets/images/photo-product-71-v2.webp' where demo = true and public_id = 71 and name = 'Café coado da Serra' and image = 'assets/images/prod-cafe-serra.webp';
update public.products set image = 'assets/images/photo-product-72-v2.webp' where demo = true and public_id = 72 and name = 'Cappuccino cremoso' and image = 'assets/images/prod-cafe-serra.webp';
update public.products set image = 'assets/images/photo-product-73-v2.webp' where demo = true and public_id = 73 and name = 'Pão de queijo grande' and image = 'assets/images/prod-queijo-coalho.webp';
update public.products set image = 'assets/images/photo-product-74-v2.webp' where demo = true and public_id = 74 and name = 'Sanduíche natural de frango' and image = 'assets/images/product-bakery.webp';
update public.products set image = 'assets/images/photo-product-75-v2.webp' where demo = true and public_id = 75 and name = 'Bolo de banana com canela' and image = 'assets/images/prod-banana.webp';
update public.products set image = 'assets/images/photo-product-76-v2.webp' where demo = true and public_id = 76 and name = 'Alface crespa' and image = 'assets/images/prod-alface.webp';
update public.products set image = 'assets/images/photo-product-77-v2.webp' where demo = true and public_id = 77 and name = 'Cheiro-verde' and image = 'assets/images/product-produce.webp';
update public.products set image = 'assets/images/photo-product-78-v2.webp' where demo = true and public_id = 78 and name = 'Tomate da Serra 1 kg' and image = 'assets/images/prod-tomate.webp';
update public.products set image = 'assets/images/photo-product-79-v2.webp' where demo = true and public_id = 79 and name = 'Cenoura 1 kg' and image = 'assets/images/prod-cenoura.webp';
update public.products set image = 'assets/images/photo-product-80-v2.webp' where demo = true and public_id = 80 and name = 'Cesta de salada' and image = 'assets/images/prod-cesta-hortalicas.webp';
update public.products set image = 'assets/images/photo-product-81-v2.webp' where demo = true and public_id = 81 and name = 'Mel artesanal 500 g' and image = 'assets/images/prod-mel.webp';
update public.products set image = 'assets/images/photo-product-82-v2.webp' where demo = true and public_id = 82 and name = 'Geleia de goiaba 250 g' and image = 'assets/images/prod-geleia-goiaba.webp';
update public.products set image = 'assets/images/photo-product-83-v2.webp' where demo = true and public_id = 83 and name = 'Rapadura tradicional' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-84-v2.webp' where demo = true and public_id = 84 and name = 'Farinha de mandioca 1 kg' and image = 'assets/images/product-artisanal.webp';
update public.products set image = 'assets/images/photo-product-85-v2.webp' where demo = true and public_id = 85 and name = 'Queijo coalho artesanal 500 g' and image = 'assets/images/prod-queijo-coalho.webp';
update public.products set image = 'assets/images/photo-product-86-v2.webp' where demo = true and public_id = 86 and name = 'Banana prata 1 kg' and image = 'assets/images/prod-banana.webp';
update public.products set image = 'assets/images/photo-product-87-v2.webp' where demo = true and public_id = 87 and name = 'Macaxeira 1 kg' and image = 'assets/images/prod-macaxeira.webp';
update public.products set image = 'assets/images/photo-product-88-v2.webp' where demo = true and public_id = 88 and name = 'Batata-doce 1 kg' and image = 'assets/images/product-produce.webp';
update public.products set image = 'assets/images/photo-product-89-v2.webp' where demo = true and public_id = 89 and name = 'Feijão verde 1 kg' and image = 'assets/images/product-produce.webp';
update public.products set image = 'assets/images/photo-product-90-v2.webp' where demo = true and public_id = 90 and name = 'Cesta da roça' and image = 'assets/images/prod-cesta-organica.webp';
update public.products set image = 'assets/images/photo-product-1001-v2.webp' where demo = true and public_id = 1001 and name = 'Arroz de galinha' and image = 'assets/images/prod-galinha.webp';
update public.products set image = 'assets/images/photo-product-1003-v2.webp' where demo = true and public_id = 1003 and name = 'Almoço vegetariano de legumes' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-1005-v2.webp' where demo = true and public_id = 1005 and name = 'Suco de cajá 400 ml' and image = 'assets/images/prod-caja.webp';
update public.products set image = 'assets/images/photo-product-1007-v2.webp' where demo = true and public_id = 1007 and name = 'Tapioca com queijo coalho' and image = 'assets/images/prod-tapioca.webp';
update public.products set image = 'assets/images/photo-product-1009-v2.webp' where demo = true and public_id = 1009 and name = 'Bolo de milho — fatia' and image = 'assets/images/prod-bolo-milho.webp';
update public.products set image = 'assets/images/photo-product-1010-v2.webp' where demo = true and public_id = 1010 and name = 'Café coado 200 ml' and image = 'assets/images/prod-cafe-coado.webp';
update public.products set image = 'assets/images/photo-product-1011-v2.webp' where demo = true and public_id = 1011 and name = 'Cesta de hortaliças' and image = 'assets/images/prod-cesta-hortalicas.webp';
update public.products set image = 'assets/images/photo-product-1012-v2.webp' where demo = true and public_id = 1012 and name = 'Banana prata 1 kg' and image = 'assets/images/prod-banana.webp';
update public.products set image = 'assets/images/photo-product-1014-v2.webp' where demo = true and public_id = 1014 and name = 'Geleia de goiaba 250 g' and image = 'assets/images/prod-geleia-goiaba.webp';
update public.products set image = 'assets/images/photo-product-1015-v2.webp' where demo = true and public_id = 1015 and name = 'Feijão verde 500 g' and image = 'assets/images/prod-feijao-verde.webp';
update public.products set image = 'assets/images/photo-product-1016-v2.webp' where demo = true and public_id = 1016 and name = 'Baião vegetariano' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-1017-v2.webp' where demo = true and public_id = 1017 and name = 'Carne de panela com arroz' and image = 'assets/images/prod-carne-panela.webp';
update public.products set image = 'assets/images/photo-product-1018-v2.webp' where demo = true and public_id = 1018 and name = 'Almoço vegetariano de legumes' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-1019-v2.webp' where demo = true and public_id = 1019 and name = 'Peixe com purê de macaxeira' and image = 'assets/images/prod-peixe-pure.webp';
update public.products set image = 'assets/images/photo-product-1020-v2.webp' where demo = true and public_id = 1020 and name = 'Suco de cajá 400 ml' and image = 'assets/images/prod-caja.webp';
update public.products set image = 'assets/images/photo-product-1021-v2.webp' where demo = true and public_id = 1021 and name = 'Cuscuz com ovo' and image = 'assets/images/prod-cuscuz-ovo.webp';
update public.products set image = 'assets/images/photo-product-1022-v2.webp' where demo = true and public_id = 1022 and name = 'Tapioca com queijo coalho' and image = 'assets/images/prod-tapioca.webp';
update public.products set image = 'assets/images/photo-product-1023-v2.webp' where demo = true and public_id = 1023 and name = 'Pão de queijo — 3 unidades' and image = 'assets/images/prod-pao-queijo.webp';
update public.products set image = 'assets/images/photo-product-1025-v2.webp' where demo = true and public_id = 1025 and name = 'Café coado 200 ml' and image = 'assets/images/prod-cafe-coado.webp';
update public.products set image = 'assets/images/photo-product-1026-v2.webp' where demo = true and public_id = 1026 and name = 'Cesta de hortaliças' and image = 'assets/images/prod-cesta-hortalicas.webp';
update public.products set image = 'assets/images/photo-product-1027-v2.webp' where demo = true and public_id = 1027 and name = 'Banana prata 1 kg' and image = 'assets/images/prod-banana.webp';
update public.products set image = 'assets/images/photo-product-1029-v2.webp' where demo = true and public_id = 1029 and name = 'Geleia de goiaba 250 g' and image = 'assets/images/prod-geleia-goiaba.webp';
update public.products set image = 'assets/images/photo-product-1030-v2.webp' where demo = true and public_id = 1030 and name = 'Feijão verde 500 g' and image = 'assets/images/prod-feijao-verde.webp';
update public.products set image = 'assets/images/photo-product-1032-v2.webp' where demo = true and public_id = 1032 and name = 'Carne de panela com arroz' and image = 'assets/images/prod-carne-panela.webp';
update public.products set image = 'assets/images/photo-product-1033-v2.webp' where demo = true and public_id = 1033 and name = 'Almoço vegetariano de legumes' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-1034-v2.webp' where demo = true and public_id = 1034 and name = 'Peixe com purê de macaxeira' and image = 'assets/images/prod-peixe-pure.webp';
update public.products set image = 'assets/images/photo-product-1035-v2.webp' where demo = true and public_id = 1035 and name = 'Suco de cajá 400 ml' and image = 'assets/images/prod-caja.webp';
update public.products set image = 'assets/images/photo-product-1036-v2.webp' where demo = true and public_id = 1036 and name = 'Cuscuz com ovo' and image = 'assets/images/prod-cuscuz-ovo.webp';
update public.products set image = 'assets/images/photo-product-1037-v2.webp' where demo = true and public_id = 1037 and name = 'Tapioca com queijo coalho' and image = 'assets/images/prod-tapioca.webp';
update public.products set image = 'assets/images/photo-product-1038-v2.webp' where demo = true and public_id = 1038 and name = 'Pão de queijo — 3 unidades' and image = 'assets/images/prod-pao-queijo.webp';
update public.products set image = 'assets/images/photo-product-1040-v2.webp' where demo = true and public_id = 1040 and name = 'Café coado 200 ml' and image = 'assets/images/prod-cafe-coado.webp';
update public.products set image = 'assets/images/photo-product-1041-v2.webp' where demo = true and public_id = 1041 and name = 'Cesta de hortaliças' and image = 'assets/images/prod-cesta-hortalicas.webp';
update public.products set image = 'assets/images/photo-product-1042-v2.webp' where demo = true and public_id = 1042 and name = 'Banana prata 1 kg' and image = 'assets/images/prod-banana.webp';
update public.products set image = 'assets/images/photo-product-1043-v2.webp' where demo = true and public_id = 1043 and name = 'Tomate 1 kg' and image = 'assets/images/prod-tomate.webp';
update public.products set image = 'assets/images/photo-product-1044-v2.webp' where demo = true and public_id = 1044 and name = 'Geleia de goiaba 250 g' and image = 'assets/images/prod-geleia-goiaba.webp';
update public.products set image = 'assets/images/photo-product-1045-v2.webp' where demo = true and public_id = 1045 and name = 'Feijão verde 500 g' and image = 'assets/images/prod-feijao-verde.webp';
update public.products set image = 'assets/images/photo-product-1046-v2.webp' where demo = true and public_id = 1046 and name = 'Frango com cuscuz' and image = 'assets/images/prod-galinha.webp';
update public.products set image = 'assets/images/photo-product-1047-v2.webp' where demo = true and public_id = 1047 and name = 'Carne de panela com arroz' and image = 'assets/images/prod-carne-panela.webp';
update public.products set image = 'assets/images/photo-product-1048-v2.webp' where demo = true and public_id = 1048 and name = 'Almoço vegetariano de legumes' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-1049-v2.webp' where demo = true and public_id = 1049 and name = 'Peixe com purê de macaxeira' and image = 'assets/images/prod-peixe-pure.webp';
update public.products set image = 'assets/images/photo-product-1050-v2.webp' where demo = true and public_id = 1050 and name = 'Suco de cajá 400 ml' and image = 'assets/images/prod-caja.webp';
update public.products set image = 'assets/images/photo-product-1051-v2.webp' where demo = true and public_id = 1051 and name = 'Cuscuz com ovo' and image = 'assets/images/prod-cuscuz-ovo.webp';
update public.products set image = 'assets/images/photo-product-1052-v2.webp' where demo = true and public_id = 1052 and name = 'Tapioca com queijo coalho' and image = 'assets/images/prod-tapioca.webp';
update public.products set image = 'assets/images/photo-product-1053-v2.webp' where demo = true and public_id = 1053 and name = 'Pão de queijo — 3 unidades' and image = 'assets/images/prod-pao-queijo.webp';
update public.products set image = 'assets/images/photo-product-1055-v2.webp' where demo = true and public_id = 1055 and name = 'Café coado 200 ml' and image = 'assets/images/prod-cafe-coado.webp';
update public.products set image = 'assets/images/photo-product-1056-v2.webp' where demo = true and public_id = 1056 and name = 'Cesta de hortaliças' and image = 'assets/images/prod-cesta-hortalicas.webp';
update public.products set image = 'assets/images/photo-product-1057-v2.webp' where demo = true and public_id = 1057 and name = 'Banana prata 1 kg' and image = 'assets/images/prod-banana.webp';
update public.products set image = 'assets/images/photo-product-1058-v2.webp' where demo = true and public_id = 1058 and name = 'Cenoura 1 kg' and image = 'assets/images/prod-cenoura.webp';
update public.products set image = 'assets/images/photo-product-1059-v2.webp' where demo = true and public_id = 1059 and name = 'Geleia de goiaba 250 g' and image = 'assets/images/prod-geleia-goiaba.webp';
update public.products set image = 'assets/images/photo-product-1060-v2.webp' where demo = true and public_id = 1060 and name = 'Feijão verde 500 g' and image = 'assets/images/prod-feijao-verde.webp';
update public.products set image = 'assets/images/photo-product-1061-v2.webp' where demo = true and public_id = 1061 and name = 'Marmita vegetariana da casa' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-1062-v2.webp' where demo = true and public_id = 1062 and name = 'Baião vegetariano individual' and image = 'assets/images/prod-almoco-veg.webp';
update public.products set image = 'assets/images/photo-product-1063-v2.webp' where demo = true and public_id = 1063 and name = 'Escondidinho de legumes' and image = 'assets/images/prod-escondidinho-veg.webp';
update public.stores set cover = 'assets/images/photo-store-6-v2.webp' where demo = true and public_id = 6 and name = 'Pão da Praça' and cover = 'assets/images/product-bakery.webp';
update public.stores set cover = 'assets/images/photo-store-7-v2.webp' where demo = true and public_id = 7 and name = 'Padaria Neblina' and cover = 'assets/images/cover-forno.webp';
update public.stores set cover = 'assets/images/photo-store-8-v2.webp' where demo = true and public_id = 8 and name = 'Doce Encanto da Serra' and cover = 'assets/images/product-artisanal.webp';
update public.stores set cover = 'assets/images/photo-store-9-v2.webp' where demo = true and public_id = 9 and name = 'Açúcar & Canela' and cover = 'assets/images/product-artisanal.webp';
update public.stores set cover = 'assets/images/photo-store-10-v2.webp' where demo = true and public_id = 10 and name = 'Flor de Cacau' and cover = 'assets/images/product-artisanal.webp';
update public.stores set cover = 'assets/images/photo-store-11-v2.webp' where demo = true and public_id = 11 and name = 'Chapa do Norte' and cover = 'assets/images/product-regional.webp';
update public.stores set cover = 'assets/images/photo-store-12-v2.webp' where demo = true and public_id = 12 and name = 'Ponto do Cuscuz' and cover = 'assets/images/product-caseiro.webp';
update public.stores set cover = 'assets/images/photo-store-13-v2.webp' where demo = true and public_id = 13 and name = 'Massa da Serra' and cover = 'assets/images/product-caseiro.webp';
update public.stores set cover = 'assets/images/photo-store-14-v2.webp' where demo = true and public_id = 14 and name = 'Panelinha Ibiapaba' and cover = 'assets/images/product-caseiro.webp';
update public.stores set cover = 'assets/images/photo-store-15-v2.webp' where demo = true and public_id = 15 and name = 'Café Jatobá' and cover = 'assets/images/prod-cafe-serra.webp';
update public.stores set cover = 'assets/images/photo-store-16-v2.webp' where demo = true and public_id = 16 and name = 'Horta Pedra Branca' and cover = 'assets/images/product-produce.webp';
update public.stores set cover = 'assets/images/photo-store-17-v2.webp' where demo = true and public_id = 17 and name = 'Mel & Raiz da Serra' and cover = 'assets/images/cover-sitio.webp';
update public.stores set cover = 'assets/images/photo-store-18-v2.webp' where demo = true and public_id = 18 and name = 'Roçado da Ibiapaba' and cover = 'assets/images/product-produce.webp';
update public.stores set cover = 'assets/images/photo-store-101-v2.webp' where demo = true and public_id = 101 and name = 'Cozinha de Viçosa · Demo' and cover = 'assets/images/product-caseiro.webp';
update public.stores set cover = 'assets/images/photo-store-102-v2.webp' where demo = true and public_id = 102 and name = 'Forno de Viçosa · Demo' and cover = 'assets/images/product-bakery.webp';
update public.stores set cover = 'assets/images/photo-store-103-v2.webp' where demo = true and public_id = 103 and name = 'Horta de Viçosa · Demo' and cover = 'assets/images/product-produce.webp';
update public.stores set cover = 'assets/images/photo-store-104-v2.webp' where demo = true and public_id = 104 and name = 'Mesa de Carnaubal · Demo' and cover = 'assets/images/product-caseiro.webp';
update public.stores set cover = 'assets/images/photo-store-105-v2.webp' where demo = true and public_id = 105 and name = 'Pão de Carnaubal · Demo' and cover = 'assets/images/product-bakery.webp';
update public.stores set cover = 'assets/images/photo-store-106-v2.webp' where demo = true and public_id = 106 and name = 'Roça de Carnaubal · Demo' and cover = 'assets/images/product-produce.webp';
update public.stores set cover = 'assets/images/photo-store-107-v2.webp' where demo = true and public_id = 107 and name = 'Cozinha de Croatá · Demo' and cover = 'assets/images/product-caseiro.webp';
update public.stores set cover = 'assets/images/photo-store-108-v2.webp' where demo = true and public_id = 108 and name = 'Café de Croatá · Demo' and cover = 'assets/images/product-bakery.webp';
update public.stores set cover = 'assets/images/photo-store-109-v2.webp' where demo = true and public_id = 109 and name = 'Colheita de Croatá · Demo' and cover = 'assets/images/product-produce.webp';
update public.stores set cover = 'assets/images/photo-store-110-v2.webp' where demo = true and public_id = 110 and name = 'Mesa do Ipu · Demo' and cover = 'assets/images/product-caseiro.webp';
update public.stores set cover = 'assets/images/photo-store-111-v2.webp' where demo = true and public_id = 111 and name = 'Forno do Ipu · Demo' and cover = 'assets/images/product-bakery.webp';
update public.stores set cover = 'assets/images/photo-store-112-v2.webp' where demo = true and public_id = 112 and name = 'Horta do Ipu · Demo' and cover = 'assets/images/product-produce.webp';
