export const TOPICS=['meal','drink','snack','breakfast','dessert','produce','catalog'];
export const ACTIONS=['recommend','list','alternative','refine','switch','fact','clarify','confirm','chat'];
export const CONFIDENCE={low:0.42,medium:0.62,high:0.78};
const CONCEPTS={
  meal:['almoco','refeicao','comida','prato','jantar','rango','marmita'],
  snack:['lanche','tapioca','pao','sanduiche','salgado','petisco'],
  breakfast:['desjejum','matinal','manha','comecar'],
  dessert:['sobremesa','doce','bolo','docinho'],
  drink:['bebida','beber','suco','refri','cafe','agua','sede','tomar'],
  produce:['produtor','roca','horta','hortalica','verdura','legume','organico','local']
};
const CHAT=['oi','ola','bom','boa','salve','eai','ai','tudo','obrigado','obrigada','valeu'];
const CONFIRM=['sim','s','ss','claro','pode','manda','quero','beleza','certo','positivo'];
const SWITCH=['agora','prefiro','troca','esquece','verdade','melhor','mudei'];
const ALTERNATIVE=['outro','outra','diferente','mais','alternativa'];

export function plain(text){return String(text||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/([a-z])\1{2,}/g,'$1').replace(/[^a-z0-9$.,\s]/g,' ').replace(/\s+/g,' ').trim();}
export function distance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old;}}return row[b.length];}
function close(word,target){if(word===target||word.startsWith(target.slice(0,Math.max(4,target.length-2))))return true;const limit=target.length>=7?2:target.length>=4?1:0;return limit>0&&Math.abs(word.length-target.length)<=limit&&distance(word,target)<=limit;}
export function tokens(text){return plain(text).split(' ').filter(Boolean);}
function conceptScores(text){const words=tokens(text),scores={};for(const [concept,terms] of Object.entries(CONCEPTS)){scores[concept]=0;for(const word of words)if(terms.some(term=>close(word,term)))scores[concept]++;}return scores;}
function anyClose(words,terms){return words.some(word=>terms.some(term=>close(word,term)));}

function money(text){const clean=plain(text),values=[];for(const pattern of [/r\$\s*(\d+(?:[.,]\d{1,2})?)/g,/(\d+(?:[.,]\d{1,2})?)\s*reais?\b/g,/(?:ate|limite|orcamento|maximo)\D{0,12}(\d+(?:[.,]\d{1,2})?)/g])for(const match of clean.matchAll(pattern))values.push(Math.round(Number(match[1].replace(',','.'))*100));return values.length?Math.max(...values.filter(Number.isFinite)):null;}
export function hardConstraints(current,previousUser=[]){const clean=plain(current),forgetBudget=/(?:sem|tira|remove|esquece|ignora)\s+(?:o\s+)?(?:limite|orcamento)/.test(clean)||/pode\s+(?:passar|ultrapassar)/.test(clean);let budget=forgetBudget?null:money(current),budgetExplicit=forgetBudget||budget!==null;if(!budgetExplicit)for(const text of [...previousUser].reverse()){budget=money(text);if(budget!==null)break;}const exclusions=[];for(const match of clean.matchAll(/\b(?:sem|nao quero|evite)\s+(?:ser\s+)?(?:(?:da|de|do)\s+)?([a-z][a-z0-9-]*)/g))exclusions.push(match[1]);return {budget,budgetScope:/(?:sem contar|fora|nao inclua).{0,15}(?:entrega|taxa)|so\s+(?:os\s+)?produtos/.test(clean)?'products':'total',exclusions:[...new Set(exclusions)],budgetExplicit};}

export function localIntent(current,previous=null,{pending=false}={}){const clean=plain(current),words=tokens(current),confirm=pending&&words.length<=4&&anyClose(words,CONFIRM),scores=confirm?{}:conceptScores(current),components=Object.entries(scores).filter(([,score])=>score>0).sort((a,b)=>b[1]-a[1]).map(([name])=>name),alternative=anyClose(words,ALTERNATIVE),chat=!components.length&&!confirm&&words.length<=5&&anyClose(words,CHAT),list=words.some(word=>close(word,'listar')||close(word,'mostrar')||close(word,'opcoes'));let topic=components[0]||null,switching=anyClose(words,SWITCH)||Boolean(topic&&previous?.topic&&topic!==previous.topic);let fact=null;if(/entrega|taxa|frete/.test(clean))fact='delivery_fee';else if(/mais barato|menor preco/.test(clean))fact='cheapest';else if(/mais caro|maior preco/.test(clean))fact='most_expensive';else if(/mais pedido|mais vendido|popular/.test(clean))fact='most_ordered';else if(/quanto custa|qual.*preco/.test(clean))fact='price';else if(/disponiv|existe|tem no catalogo|quantas? opcoes/.test(clean))fact='availability';if(!topic&&(alternative||fact||confirm||(!chat&&previous?.topic))&&previous&&!switching){topic=previous.topic;if(alternative||confirm)components.push(...(previous.components||[]));}const preferences=[];if(anyClose(words,['vegano']))preferences.push('vegano');if(anyClose(words,['vegetariano']))preferences.push('vegetariano');const signal=Math.max(0,...Object.values(scores)),confidence=fact||confirm||chat?0.9:signal?Math.min(.94,.68+signal*.1):previous&&topic?.58:.12,action=fact?'fact':confirm?'confirm':chat?'chat':switching?'switch':alternative?'alternative':list?'list':topic?'recommend':'clarify';return {topic:topic||null,action,fact,categories:[],preferences,exclusions:[],components:[...new Set(components)],searchTerms:words,serves:null,keepPreviousContext:!switching&&Boolean(previous),confidence};}

export function conversationState(history,products=[]){let intent=null,pendingQuestion=false;const productIds=[],storeIds=[];for(const message of history||[]){if(message?.role==='user')intent=localIntent(message.content,intent,{pending:pendingQuestion});if(message?.role==='assistant'){pendingQuestion=/\?\s*$/.test(String(message.content||''));for(const item of products)if(plain(message.content).includes(plain(item.name))){productIds.push(item.id);storeIds.push(item.storeId);}}}return {activeTopic:intent?.topic||null,activeComponents:intent?.components||[],activePreferences:intent?.preferences||[],lastRecommendedProductIds:[...new Set(productIds)],lastRecommendedStoreIds:[...new Set(storeIds)],pendingQuestion,lastAction:intent?.action||null,intent};}
export function normalizeIntent(value,fallback){const raw=value&&typeof value==='object'?value:{},topic=TOPICS.includes(raw.topic)?raw.topic:fallback.topic,action=ACTIONS.includes(raw.action)?raw.action:fallback.action,list=(key,allowed=null)=>Array.isArray(raw[key])?[...new Set(raw[key].filter(x=>typeof x==='string'&&(!allowed||allowed.includes(x))).slice(0,8))]:fallback[key]||[];return {topic,action,fact:typeof raw.fact==='string'?raw.fact:fallback.fact,categories:list('categories'),preferences:list('preferences',['vegano','vegetariano']),exclusions:list('exclusions'),components:list('components',TOPICS.filter(x=>x!=='catalog')),searchTerms:list('searchTerms'),serves:Number.isInteger(raw.serves)&&raw.serves>0&&raw.serves<=20?raw.serves:null,keepPreviousContext:Boolean(raw.keepPreviousContext),confidence:Math.max(0,Math.min(1,Number(raw.confidence)||fallback.confidence||0))};}
export function parseJsonObject(text){const source=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''),start=source.indexOf('{'),end=source.lastIndexOf('}');if(start<0||end<=start)return null;try{return JSON.parse(source.slice(start,end+1));}catch{return null;}}
export function bundleTotal(items,mode,budgetScope='total'){const products=items.reduce((sum,item)=>sum+item.price,0);if(mode==='pickup'||budgetScope==='products')return products;const fees=new Map();for(const item of items)fees.set(item.storeId,item.fee);return products+[...fees.values()].reduce((sum,fee)=>sum+fee,0);}
